export const PERMISSIONS = {
  DASHBOARD_VUE_GENERALE: "DASHBOARD_VUE_GENERALE",
  DASHBOARD_KPI_GLOBAUX: "DASHBOARD_KPI_GLOBAUX",

  PROJETS_VUE_ENSEMBLE: "PROJETS_VUE_ENSEMBLE",
  PROJETS_FICHE_IDENTIFICATION: "PROJETS_FICHE_IDENTIFICATION",
  PROJETS_LIVRABLES: "PROJETS_LIVRABLES",
  PROJETS_COUT_ACTUALISE: "PROJETS_COUT_ACTUALISE",
  PROJETS_COUT_PREVISIONNEL: "PROJETS_COUT_PREVISIONNEL",
  PROJETS_DI: "PROJETS_DI",
  PROJETS_TCC: "PROJETS_TCC",
  PROJETS_FACTURATION: "PROJETS_FACTURATION",
  PROJETS_STATISTIQUE: "PROJETS_STATISTIQUE",

  ADMIN_UTILISATEURS: "ADMIN_UTILISATEURS",
  ADMIN_ROLES: "ADMIN_ROLES",
} as const;

export const DASHBOARD_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_KPI_GLOBAUX,
  PERMISSIONS.DASHBOARD_VUE_GENERALE,
];

export const PROJETS_PERMISSIONS = [
  PERMISSIONS.PROJETS_COUT_ACTUALISE,
  PERMISSIONS.PROJETS_COUT_PREVISIONNEL,
  PERMISSIONS.PROJETS_DI,
  PERMISSIONS.PROJETS_FACTURATION,
  PERMISSIONS.PROJETS_FICHE_IDENTIFICATION,
  PERMISSIONS.PROJETS_LIVRABLES,
  PERMISSIONS.PROJETS_STATISTIQUE,
  PERMISSIONS.PROJETS_TCC,
  PERMISSIONS.PROJETS_VUE_ENSEMBLE,
];

export const ADMIN_PERMISSIONS = [
  PERMISSIONS.ADMIN_ROLES,
  PERMISSIONS.ADMIN_UTILISATEURS,
];
